/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import controlador.ConductorDAO;
import controlador.Conexion;
import controlador.FuncionarioDAO;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.ConductorVO;

/**
 *
 * @author Usuario
 */
public class Conductor extends javax.swing.JFrame {
private Connection conexion;
    private Conexion conector;
    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form Conductor
     */java.sql.Date sqlDate;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivo de Imagen", "jpg");
    String rutaFoto,rutaFotoLinc, ident, nombre, apellido, celular, direccion, correo,    restLin, imgLin, fechaDC;
    String catLin, ciuLin;
    boolean estado;
    Date vigLin;
    String id2;
    Calendar vigLin1;
    ImageIcon img;
    ArrayList<ConductorVO> datosFuncionario;
    ArrayList<String> datosInicio;
    ConductorVO transFuncionario;
    boolean bImg=false;
    String id_func="";
     java.sql.Date dateDB;
//    ArrayList<FuncionarioVO> datosFuncionario;
//    FuncionarioVO transFuncionario;
    DefaultTableModel modelo;
    int nivel,posicionUsuario = -1;
    boolean guardarEditar=false;
    ConductorDAO BDConductor;
    ArrayList<String> datosFuncionarioTabla;
    String fecha;
    
    public Conductor() {
        initComponents();
        
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(null);
        bloquearCajas();
       
        BDConductor=new ConductorDAO();
        

        
        datosFuncionario=new ArrayList<ConductorVO>();
        datosInicio=new ArrayList<String>();
        datosFuncionarioTabla=new ArrayList<String>();
        datosFuncionarioTabla=BDConductor.buscarConductor();
        datosInicio=BDConductor.buscarConductor();
       
        modelo = new DefaultTableModel();
        modelo.addColumn("Ident.");
        modelo.addColumn("Nombre");
        modelo.addColumn("Celular");
        modelo.addColumn("correo");
        modelo.addColumn("Dirección");
        modelo.addColumn("Categoria Licencia");
        modelo.addColumn("Vigencia Licencia");
        modelo.addColumn("Ciudad Licencia");
        modelo.addColumn("Restriccion Licencia");
        //modelo.addColumn("Edad");
        this.jTConduc.setModel(modelo);
        this.jTConduc.getColumn(jTConduc.getColumnName(0)).setMaxWidth(100);
        this.jTConduc.getColumn(jTConduc.getColumnName(4)).setMaxWidth(100);
        this.jTConduc.getColumn(jTConduc.getColumnName(8)).setMaxWidth(100);
         BDConductor=new ConductorDAO();
         cargarTablaInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFCelular = new javax.swing.JTextField();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTConduc = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLFoto = new javax.swing.JLabel();
        jBFotoCond = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFRestLicenCond = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jCBCatLicen = new javax.swing.JComboBox<>();
        jCBCiudadLicen = new javax.swing.JComboBox<>();
        jBImgLicen = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jBVerLin = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conductor");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso Conductor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Identificación:");

        jTFIdent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdentKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Dirección:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("E-Mail:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Celular:");

        jTFCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCelularActionPerformed(evt);
            }
        });
        jTFCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCelularKeyTyped(evt);
            }
        });

        jBNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jBNuevo.setBorder(null);
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setBackground(new java.awt.Color(255, 255, 255));
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jBGuardar.setBorder(null);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBEditar.setBackground(new java.awt.Color(255, 255, 255));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jBEditar.setBorder(null);
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jBBuscar.setBorder(null);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jBEliminar.setBorder(null);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jTConduc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTConduc.setEnabled(false);
        jScrollPane1.setViewportView(jTConduc);

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton11.setText("Salir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jBFotoCond.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBFotoCond.setText("Foto");
        jBFotoCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFotoCondActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Categoria Licencia:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Vigencia Licencia:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Ciudad Licencia:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Restricción Licencia:");

        jLabel111.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel111.setText("Imagen Licencia:");

        jCBCatLicen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jCBCatLicen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Categoria:", "A1", "A2", "B1", "B2", "B3", "C1", "C2", "C3" }));

        jCBCiudadLicen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jCBCiudadLicen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Ciudad:", "Armenia", "Bogota", "Cali", "Medellin", "Barranquilla", "Pasto", "Otra" }));

        jBImgLicen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBImgLicen.setText("Cargar");
        jBImgLicen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImgLicenActionPerformed(evt);
            }
        });

        jBVerLin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBVerLin.setText("Ver");
        jBVerLin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerLinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFCelular)
                                        .addComponent(jTFCorreo)
                                        .addComponent(jTFDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTFApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(jTFNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTFIdent))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCBCatLicen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBCiudadLicen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel111))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBImgLicen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBVerLin))
                                    .addComponent(jTFRestLicenCond))))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jBFotoCond)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 712, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTFIdent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jCBCatLicen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jCBCiudadLicen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTFRestLicenCond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel111)
                                    .addComponent(jBImgLicen)
                                    .addComponent(jBVerLin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jBFotoCond)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        activarCajas();
    }//GEN-LAST:event_jBNuevoActionPerformed
    
    public void obIDFunc(String id){
        id_func=id;
    }
    
  public void cargarTablaInicio(){
      String ver;
        
        for (int i = 0; i < datosFuncionarioTabla.size(); i=i+13) {
            ver=datosFuncionarioTabla.get(i+12);
            if (ver.equals("1")) {
              String[] datos=new String[9];
            datos[0]=datosFuncionarioTabla.get(i);
            datos[1]=datosFuncionarioTabla.get(i+1)+" "+datosFuncionarioTabla.get(i+2);
            datos[2]=datosFuncionarioTabla.get(i+4);
            datos[3]=datosFuncionarioTabla.get(i+5);
            datos[4]=datosFuncionarioTabla.get(i+6);
            datos[5]=datosFuncionarioTabla.get(i+7);
            datos[6]=datosFuncionarioTabla.get(i+8);
            datos[7]=datosFuncionarioTabla.get(i+9);
            datos[8]=datosFuncionarioTabla.get(i+10);
            modelo.addRow(datos);  
            
            ident = datosFuncionarioTabla.get(i);
            nombre = datosFuncionarioTabla.get(i+1);
            apellido = datosFuncionarioTabla.get(i+2);
            rutaFoto= datosFuncionarioTabla.get(i+3);
            celular = datosFuncionarioTabla.get(i+4);
            correo = datosFuncionarioTabla.get(i+5);
            direccion = datosFuncionarioTabla.get(i+6);
            catLin= datosFuncionarioTabla.get(i+7);
             
            ciuLin= datosFuncionarioTabla.get(i+9);
            restLin= datosFuncionarioTabla.get(i+10);
            rutaFotoLinc=datosFuncionarioTabla.get(i+11);
            fechaDC=datosFuncionarioTabla.get(i+8);
                try {
                    vigLin=formato.parse(fechaDC);
                } catch (ParseException ex) {
                    Logger.getLogger(Conductor.class.getName()).log(Level.SEVERE, null, ex);
                }
            fechaDC=formato.format(vigLin);
            String date = fechaDC;
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy"); // your template here
            java.util.Date dateStr;
             try {
                 dateStr = formatter.parse(date);
                 dateDB = new java.sql.Date(dateStr.getTime());
             } catch (ParseException ex) {
                 Logger.getLogger(Conductor.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            
//            java.sql.Date sqlDate = new java.sql.Date(vigLin.getTime());
            
           estado=true;
             
            
             
            transFuncionario = new ConductorVO(ident, nombre, apellido, rutaFoto, celular, correo, direccion, catLin, dateDB, ciuLin, restLin,rutaFotoLinc,id_func, estado);
            datosFuncionario.add(transFuncionario);
            
            }
            
        }
       
 }
    
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
if(guardarEditar==false){
        
        if (guardarDatos() == true) {
            JOptionPane.showMessageDialog(null,
                    "Guardado con exito...");
             posicionUsuario=-1;
            cargarTabla();
            limpiarCajas();
            bloquearCajas();
           
        
        } else {
            JOptionPane.showMessageDialog(null,
                    "Error de datos");
        }
        
       }else{
           
           if(modificarDatos()==true){
               JOptionPane.showMessageDialog(null,
                    "Modificado con exito...");
            limpiarCajas();
            bloquearCajas();
            guardarEditar=false;
           }else {
            JOptionPane.showMessageDialog(null,
                    "Error de datos");
        }
       }    }//GEN-LAST:event_jBGuardarActionPerformed

    public boolean modificarDatos() {
        
        if (validarCajas() == true) {
            ident = jTFIdent.getText();
            nombre = jTFNombre.getText();
            apellido = jTFApellido.getText();
            celular = jTFCelular.getText();
            correo = jTFCorreo.getText();
            direccion = jTFDireccion.getText();
            catLin= (String)(jCBCatLicen.getSelectedItem());
            vigLin1=dateChooserCombo1.getSelectedDate();
            ciuLin= (String)(jCBCiudadLicen.getSelectedItem());
            restLin= jTFRestLicenCond.getText();
            vigLin=vigLin1.getTime();
            fechaDC=formato.format(vigLin);
            String date = fechaDC;
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy"); // your template here
            java.util.Date dateStr;
             try {
                 dateStr = formatter.parse(date);
                 dateDB = new java.sql.Date(dateStr.getTime());
             } catch (ParseException ex) {
                 Logger.getLogger(Conductor.class.getName()).log(Level.SEVERE, null, ex);
             }
            estado=true;
            transFuncionario = new ConductorVO(
                    ident, nombre, apellido, rutaFoto,  celular, correo, direccion,catLin,dateDB, ciuLin, restLin,rutaFotoLinc,id_func,estado);
            
            datosFuncionario.set(posicionUsuario,transFuncionario);
                       
            BDConductor.editarConductor(transFuncionario,id2);
            for (int i = jTConduc.getRowCount()-1; i >=0; i--) {
            modelo.removeRow(i);    
            }
                           
            for (int i = 0; i < datosFuncionario.size(); i++) {
                String[] datos = new String[9];
        datos[0] = datosFuncionario.get(i).getIdentificacion();
        datos[1] = datosFuncionario.get(i).getNombre()+" "+datosFuncionario.get(i).getApellido();
        datos[2] = datosFuncionario.get(i).getCelular();
        datos[3] = datosFuncionario.get(i).getCorreo();
        datos[4] = datosFuncionario.get(i).getDireccion();
        datos[5] = datosFuncionario.get(i).getCatLin();
        fechaDC=formato.format(datosFuncionario.get(i).getVigLin());
        datos[6] = fechaDC;
        datos[7] = datosFuncionario.get(i).getCiuLin();
        datos[8] = datosFuncionario.get(i).getRestLin();
        
       
      
        modelo.addRow(datos);
            }
                  
                    
            
            return true;
        } else {
            return false;
        }
    }
    
    private void jBFotoCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFotoCondActionPerformed
         jLFoto.setIcon(cargarFoto());
    }//GEN-LAST:event_jBFotoCondActionPerformed

    private void jBImgLicenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImgLicenActionPerformed
        img=cargarFotoLicencia();
        jBVerLin.setEnabled(true);
    }//GEN-LAST:event_jBImgLicenActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        try {
            String buscaIdent = JOptionPane.showInputDialog(
                    "Ingresar Identificación para editar");
            buscarUsuarioEditar(buscaIdent);
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        try {
            String buscaIdent = JOptionPane.showInputDialog("Ingresar identificacion para eliminar");
            //se llama el metodo buscarUsuarioEditar y se envia la variable buscaident la cual posee la identificacion
            buscarUsuarioElm(buscaIdent);
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
    String buscaIdent = JOptionPane.showInputDialog(
       "Ingresar Identificación para editar");
       buscarUsuario(buscaIdent);
        } catch (Exception e) {
         System.err.println(e);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBVerLinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerLinActionPerformed
        verLicencia();
    }//GEN-LAST:event_jBVerLinActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTFCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCelularActionPerformed

    private void jTFCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCelularKeyTyped
 char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9')
                && (caracter != '\b'/*corresponde a Back_space*/)
                && (caracter != '.')) {
            evt.consume();//ignota el evento del teclado
        }    }//GEN-LAST:event_jTFCelularKeyTyped

    private void jTFIdentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdentKeyTyped
 char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9')
                && (caracter != '\b'/*corresponde a Back_space*/)
                && (caracter != '.')) {
            evt.consume();//ignota el evento del teclado
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdentKeyTyped
     
    public void verLicencia(){
        Licencia linc=new Licencia();
        if (bImg==false) {
        linc.cargarImg(img);
        linc.setVisible(true);  
        }else if (bImg==true) {
        linc.setVisible(true);
        bImg=false;
        }
        
    }
            
    public void buscarUsuario(String busUsu) {
        boolean verificarUsu = false;
        if (datosFuncionario.isEmpty()) {
            JOptionPane.showMessageDialog(null, 
                    "No hay Usuarios Registrados");
        } else {
            for (int i = 0; i < datosFuncionario.size(); i++) {

                if (datosFuncionario.get(i).getIdentificacion().equals(busUsu)) {
                    verificarUsu = true;
                    JOptionPane.showMessageDialog(null,
                            "Información de Usuario:\nIdentificación: "
                            +datosFuncionario.get(i).getIdentificacion()+"\nNombre: "
                            +datosFuncionario.get(i).getNombre()+"\nApellido: "
                            +datosFuncionario.get(i).getApellido()+"\nCelular: "
                            +datosFuncionario.get(i).getCelular()+"\nCorreo: "
                            +datosFuncionario.get(i).getCorreo()+"\nDireccion: "
                            +datosFuncionario.get(i).getDireccion()+"\nCategoria Licencia: "        
                            +datosFuncionario.get(i).getCatLin()+"\nVigencia Licencia: "
                            +datosFuncionario.get(i).getVigLin()+"\nCiudad Licencia: "
                            +datosFuncionario.get(i).getCiuLin()+"\nRestriccion Licencia: "
                            +datosFuncionario.get(i).getRestLin());        
                           
                    

                    
                }
            }

            if (verificarUsu == false) {
                JOptionPane.showMessageDialog(null, "Identificación Incorrecta");
            }

        }
    }
    
    public void buscarUsuarioElm(String busUsu) {
             boolean verificar = false;
        if (datosFuncionario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay Usuarios Registrados");
        } else {
            
            for (int i = 0; i < datosFuncionario.size(); i++) {

                if (datosFuncionario.get(i).getIdentificacion().equals(busUsu)) {  
                     posicionUsuario = i;
                     id2=datosFuncionario.get(i).getIdentificacion();
                     System.out.println(id2);
                      BDConductor.eliminarConductor(id2);
                    datosFuncionario.remove(posicionUsuario);
                    verificar = true;
                     for (int j= jTConduc.getRowCount(); j >=0; j--) {
            modelo.removeRow(i);    
            }
                     
                    for (int j = 0; j < datosFuncionario.size(); j++) {
                String[] datos = new String[9];
        datos[0] = datosFuncionario.get(j).getIdentificacion();
        datos[1] = datosFuncionario.get(j).getNombre()+" "+datosFuncionario.get(j).getApellido();
        datos[2] = datosFuncionario.get(j).getCelular();
        datos[3] = datosFuncionario.get(j).getCorreo();
        datos[4] = datosFuncionario.get(j).getDireccion();
        datos[5] = datosFuncionario.get(j).getCatLin();
//        datos[6] = datosFuncionario.get(j).getVigLin();
        datos[7] = datosFuncionario.get(j).getCiuLin();
        datos[8] = datosFuncionario.get(j).getRestLin();
        modelo.addRow(datos);
        
       }
                  
                }
            }

            if (verificar == false) {
                JOptionPane.showMessageDialog(null, "Cedula Incorrecta");
            }
            verificar = false;
        }
                 
          
      }
        
    public ImageIcon buscImg(String fil){
        
        
        ImageIcon icon = new ImageIcon(fil);
            //extrae la imagen del icono
            Image img = icon.getImage();
            //cambiando el tamaño a la imagen
            Image newImg = img.getScaledInstance(154, 154,
                    java.awt.Image.SCALE_SMOOTH);
            //se genera un imagenIcon con la nueva imagen
            ImageIcon newIcon = new ImageIcon(newImg);
            //rutaImagen=file;
            return newIcon;
    }
    public ImageIcon buscImgLin(String fil){
        
        
        ImageIcon icon = new ImageIcon(fil);
            //extrae la imagen del icono
            Image img = icon.getImage();
            //cambiando el tamaño a la imagen
            Image newImg = img.getScaledInstance(485, 220,
                    java.awt.Image.SCALE_SMOOTH);
            //se genera un imagenIcon con la nueva imagen
            ImageIcon newIcon = new ImageIcon(newImg);
            //rutaImagen=file;
            return newIcon;
    }
    
    
    public void buscarUsuarioEditar(String busUsu) {
        bImg=false;
        Licencia linc=new Licencia();
        boolean verificar = false;
        if (datosFuncionario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay Usuarios Registrados");
        } else {
            for (int i = 0; i < datosFuncionario.size(); i++) {
                
                if (datosFuncionario.get(i).getIdentificacion().equals(busUsu)) {
                    posicionUsuario = i;
                    guardarEditar=true;
                    activarCajas();
                    jBVerLin.setEnabled(true);
                    
                    verificar = true;
                    jTFIdent.setText(datosFuncionario.get(i).getIdentificacion());
                    id2=datosFuncionario.get(i).getIdentificacion();
                    jTFNombre.setText(datosFuncionario.get(i).getNombre());
                    jTFApellido.setText(datosFuncionario.get(i).getApellido());
                    jTFCelular.setText(datosFuncionario.get(i).getCelular());
                    jTFCorreo.setText(datosFuncionario.get(i).getCorreo());
                    jTFDireccion.setText(datosFuncionario.get(i).getDireccion());
                    jTFRestLicenCond.setText(datosFuncionario.get(i).getRestLin());
                    jCBCatLicen.setSelectedItem(datosFuncionario.get(i).getCatLin());
                    //dateChooserCombo1.setCurrent(datosFuncionario.get(i).getVigLin());
                    jCBCiudadLicen.setSelectedItem(datosFuncionario.get(i).getCiuLin());
                    jLFoto.setIcon(buscImg(datosFuncionario.get(i).getRutaFoto()));
                    
                    img=(buscImgLin(datosFuncionario.get(i).getRutaFotoLin()));
                    
                    
                    
                    
                }
            }

            if (verificar == false) {
                JOptionPane.showMessageDialog(null, "Identificación Incorrecta");
            }
            verificar = false;
        }
    }
     public void cargarTabla() {
        String[] datos = new String[9];
        datos[0] = ident;
        datos[1] = nombre + " " + apellido;
        datos[2] = celular;
        datos[3] = correo;
        datos[4] = direccion;
        datos[5] = catLin;
        datos[6] = fechaDC;
        datos[7] = ciuLin;
        datos[8] = restLin;
        
        //datos[6] = edad + "";
        modelo.addRow(datos);
    }
    
       public void limpiarCajas() {
        jTFIdent.setText("");
        jTFNombre.setText("");
        jTFApellido.setText("");
        jTFCelular.setText("");
        jTFCorreo.setText("");
        jTFDireccion.setText("");
        jCBCatLicen.setSelectedIndex(0);
        dateChooserCombo1.setCurrent(Calendar.getInstance());
        jCBCiudadLicen.setSelectedIndex(0);
        jTFRestLicenCond.setText("");
        jLFoto.setIcon(null);
    }
    
       public void obtenerVigLin(){
           
           int dia, mes, anio;
           
           
           vigLin1=dateChooserCombo1.getSelectedDate();
            dia=vigLin1.get(Calendar.DAY_OF_MONTH);
            mes=vigLin1.get(Calendar.MONTH);
            anio=vigLin1.get(Calendar.YEAR);
            fecha= anio+"/"+(mes+1)+"/"+dia;
            
       }
       
    public boolean guardarDatos(){
         if (validarCajas() == true) {
            ident = jTFIdent.getText();
            nombre = jTFNombre.getText();
            apellido = jTFApellido.getText();
            celular = jTFCelular.getText();
            correo = jTFCorreo.getText();
            direccion = jTFDireccion.getText();
            catLin= (String)(jCBCatLicen.getSelectedItem());
             System.out.println(catLin);
            ciuLin= (String)(jCBCiudadLicen.getSelectedItem());
            restLin= jTFRestLicenCond.getText();
            obtenerVigLin();
            vigLin1=(dateChooserCombo1.getSelectedDate());
            vigLin=vigLin1.getTime();
            fechaDC=formato.format(vigLin);
            String date = fechaDC;
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy"); // your template here
            java.util.Date dateStr;
             try {
                 dateStr = formatter.parse(date);
                 dateDB = new java.sql.Date(dateStr.getTime());
             } catch (ParseException ex) {
                 Logger.getLogger(Conductor.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            
//            java.sql.Date sqlDate = new java.sql.Date(vigLin.getTime());
            
           estado=true;
             
            
             
            transFuncionario = new ConductorVO(ident, nombre, apellido, rutaFoto, celular, correo, direccion, catLin, dateDB, ciuLin, restLin,rutaFotoLinc,id_func, estado);
            datosFuncionario.add(transFuncionario);
//            se envian los datos que se encuentran en funvionarioVO(transfuncionario) al metodo ingresarFuncionario que se encuentra en la clase FuncionarioDAO
            BDConductor.ingresarConductor(transFuncionario);
            return true;
        } else {
            return false;
        }
    
    }
    public boolean validarCajas() {
        
        if (jTFIdent.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ingresar Identificación");
            return false;
        } else if (jTFNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ingresar Nombre");
            return false;
        } else if (jTFApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ingresar Apellido");
            return false;
        } else if (jTFCelular.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ingresar celular");
            return false;
        } else if (jTFCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ingresar correo");
            return false;
        }else if (jTFDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ingresar Dirección");
            return false;
        }else if (jTFRestLicenCond.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ingresar Restriccion de Licencia");
            return false;
        }else if (jCBCatLicen.getSelectedItem().equals("Seleccionar Categoria:")) {
            JOptionPane.showMessageDialog(null,
                    "Seleccionar Marca");
            return false;
        }else if (jCBCiudadLicen.getSelectedItem().equals("Seleccionar Ciudad:")) {
            JOptionPane.showMessageDialog(null,
                    "Seleccionar Marca");
            return false;
        }  else {
            return true;
        }
    }
    public void activarCajas(){
        
         jTFIdent.setEnabled(true);
        jTFNombre.setEnabled(true);
        jTFApellido.setEnabled(true);
        jTFCelular.setEnabled(true);
        jTFCorreo.setEnabled(true);
        jTFDireccion.setEnabled(true);
        jTFRestLicenCond.setEnabled(true);
        jCBCatLicen.setEnabled(true);
        jCBCiudadLicen.setEnabled(true);
        dateChooserCombo1.setEnabled(true);
        jBImgLicen.setEnabled(true);
        jBGuardar.setEnabled(true);
        jBNuevo.setEnabled(false);
        jBEditar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBFotoCond.setEnabled(true);
        
    }
    
    public void bloquearCajas(){
         jTFIdent.setEnabled(false);
        jTFNombre.setEnabled(false);
        jTFApellido.setEnabled(false);
        jTFCelular.setEnabled(false);
        jTFCorreo.setEnabled(false);
        jTFDireccion.setEnabled(false);
        jTFRestLicenCond.setEnabled(false);
        jCBCatLicen.setEnabled(false);
        jCBCiudadLicen.setEnabled(false);
        dateChooserCombo1.setEnabled(false);
        jBImgLicen.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBEditar.setEnabled(true);
        jBEliminar.setEnabled(true);
        jBBuscar.setEnabled(true);
        jBVerLin.setEnabled(false);
        jBFotoCond.setEnabled(false);
        
    }
            
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conductor().setVisible(true);
            }
        });
    }
    public ImageIcon cargarFoto() {
        //crea un objeto filechooser
        JFileChooser dlg = new JFileChooser();
        //del objeto creado vamos a llamar el metodo setFileFilter
        dlg.setFileFilter(filter);
        //abrimos la ventana de dialogo para escoger imagenes
        int opcion = dlg.showOpenDialog(this);
        //si hacemos clic en boton abrir
        if (opcion == JFileChooser.APPROVE_OPTION) {
            //obtener el nombre del archivo que hemos seleccionado
            String fil = dlg.getSelectedFile().getPath();
            //obtener la direccion donde se guarda la imagen
            String file = dlg.getSelectedFile().toString();
            //modiicamos la imagen~~~~~~~~
            ImageIcon icon = new ImageIcon(fil);
            //extrae la imagen del icono
            Image img = icon.getImage();
            //cambiando el tamaño a la imagen
            Image newImg = img.getScaledInstance(154, 154,
                    java.awt.Image.SCALE_SMOOTH);
            //se genera un imagenIcon con la nueva imagen
            ImageIcon newIcon = new ImageIcon(newImg);
            //rutaImagen=file;
            rutaFoto = file;
            return newIcon;
        }
        return null;
    }
    public ImageIcon cargarFotoLicencia() {
        //crea un objeto filechooser
        JFileChooser dlg = new JFileChooser();
        //del objeto creado vamos a llamar el metodo setFileFilter
        dlg.setFileFilter(filter);
        //abrimos la ventana de dialogo para escoger imagenes
        int opcion = dlg.showOpenDialog(this);
        //si hacemos clic en boton abrir
        if (opcion == JFileChooser.APPROVE_OPTION) {
            //obtener el nombre del archivo que hemos seleccionado
            String fil = dlg.getSelectedFile().getPath();
            //obtener la direccion donde se guarda la imagen
            String file = dlg.getSelectedFile().toString();
            //modiicamos la imagen~~~~~~~~
            ImageIcon icon = new ImageIcon(fil);
            //extrae la imagen del icono
            Image img = icon.getImage();
            //cambiando el tamaño a la imagen
            Image newImg = img.getScaledInstance(450, 150,
                    java.awt.Image.SCALE_SMOOTH);
            //se genera un imagenIcon con la nueva imagen
            ImageIcon newIcon = new ImageIcon(newImg);
            //rutaImagen=file;
            rutaFotoLinc = file;
            return newIcon;
        }
        return null;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBFotoCond;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBImgLicen;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBVerLin;
    private javax.swing.JButton jButton11;
    private javax.swing.JComboBox<String> jCBCatLicen;
    private javax.swing.JComboBox<String> jCBCiudadLicen;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTConduc;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFCelular;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFIdent;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFRestLicenCond;
    // End of variables declaration//GEN-END:variables

    private String String(int catLin) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
