/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

//import com.opencsv.CSVReader;
import java.awt.Color;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.ConductorVO;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {
String idFu;
private FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV","CSV (MS-DOS)","CSV (Macintosh)");
    /**
     * Creates new form MenuPrincipal
     */
    String  codigo, ident, nombre, apellido, celular,correo, direccion, grado, ciudad, nomAcu,celAcu,corrAcu,DirecAcu;
  ArrayList<ConductorVO> datosFuncionario;
    ConductorVO transFuncionario;
    public MenuPrincipal() {
        initComponents();
                getContentPane().setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jBVehiculo = new javax.swing.JButton();
        jBConductor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBSoat = new javax.swing.JButton();
        jBAsistente = new javax.swing.JButton();
        jBFuncionario = new javax.swing.JButton();
        jBEstudiante = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBAsistente1 = new javax.swing.JButton();
        jBRuta = new javax.swing.JButton();
        jBAseguradora = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBTecnomecanica = new javax.swing.JButton();
        jBLista = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIFuncionario = new javax.swing.JMenuItem();
        jMIAseguradora = new javax.swing.JMenuItem();
        jMIEstudiante = new javax.swing.JMenuItem();
        jMIConductor = new javax.swing.JMenuItem();
        jMIAsistente = new javax.swing.JMenuItem();
        jMIVehiculo = new javax.swing.JMenuItem();
        jMISoat = new javax.swing.JMenuItem();
        jMRuta = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMConsulta = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("vehiculo");

        jBVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        jBVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jBVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bus.png"))); // NOI18N
        jBVehiculo.setBorder(null);
        jBVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVehiculoActionPerformed(evt);
            }
        });

        jBConductor.setBackground(new java.awt.Color(255, 255, 255));
        jBConductor.setForeground(new java.awt.Color(255, 255, 255));
        jBConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/conductor.png"))); // NOI18N
        jBConductor.setBorder(null);
        jBConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConductorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("conductor");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("soat");

        jBSoat.setBackground(new java.awt.Color(255, 255, 255));
        jBSoat.setForeground(new java.awt.Color(255, 255, 255));
        jBSoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/soat.png"))); // NOI18N
        jBSoat.setBorder(null);
        jBSoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSoatActionPerformed(evt);
            }
        });

        jBAsistente.setBackground(new java.awt.Color(255, 255, 255));
        jBAsistente.setForeground(new java.awt.Color(255, 255, 255));
        jBAsistente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jBAsistente.setBorder(null);
        jBAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsistenteActionPerformed(evt);
            }
        });

        jBFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        jBFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jBFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/funcionario1.png"))); // NOI18N
        jBFuncionario.setBorder(null);
        jBFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFuncionarioActionPerformed(evt);
            }
        });

        jBEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        jBEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jBEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        jBEstudiante.setBorder(null);
        jBEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEstudianteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("estudiante");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("funcionario");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("asistente");

        jBAsistente1.setBackground(new java.awt.Color(255, 255, 255));
        jBAsistente1.setForeground(new java.awt.Color(255, 255, 255));
        jBAsistente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asistente.png"))); // NOI18N
        jBAsistente1.setBorder(null);
        jBAsistente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsistente1ActionPerformed(evt);
            }
        });

        jBRuta.setBackground(new java.awt.Color(255, 255, 255));
        jBRuta.setForeground(new java.awt.Color(255, 255, 255));
        jBRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ruta.png"))); // NOI18N
        jBRuta.setBorder(null);
        jBRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRutaActionPerformed(evt);
            }
        });

        jBAseguradora.setBackground(new java.awt.Color(255, 255, 255));
        jBAseguradora.setForeground(new java.awt.Color(255, 255, 255));
        jBAseguradora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aseguradora.png"))); // NOI18N
        jBAseguradora.setBorder(null);
        jBAseguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAseguradoraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("aseguradora");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("ruta");

        jBTecnomecanica.setBackground(new java.awt.Color(255, 255, 255));
        jBTecnomecanica.setForeground(new java.awt.Color(255, 255, 255));
        jBTecnomecanica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tecnomecanica.png"))); // NOI18N
        jBTecnomecanica.setBorder(null);
        jBTecnomecanica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTecnomecanicaActionPerformed(evt);
            }
        });

        jBLista.setBackground(new java.awt.Color(255, 255, 255));
        jBLista.setForeground(new java.awt.Color(255, 255, 255));
        jBLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lista.png"))); // NOI18N
        jBLista.setBorder(null);
        jBLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("tecnomecanica");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("lista estudiantes");

        jMenu1.setText("Registros");

        jMIFuncionario.setText("Ingreso Funcionario");
        jMIFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMIFuncionario);

        jMIAseguradora.setText("Ingreso Aseguradora");
        jMIAseguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAseguradoraActionPerformed(evt);
            }
        });
        jMenu1.add(jMIAseguradora);

        jMIEstudiante.setText("Ingreso Estudiante");
        jMIEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEstudianteActionPerformed(evt);
            }
        });
        jMenu1.add(jMIEstudiante);

        jMIConductor.setText("Ingreso Conductor");
        jMIConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConductorActionPerformed(evt);
            }
        });
        jMenu1.add(jMIConductor);

        jMIAsistente.setText("Ingreso Asistente");
        jMIAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAsistenteActionPerformed(evt);
            }
        });
        jMenu1.add(jMIAsistente);

        jMIVehiculo.setText("Ingreso Vehiculo");
        jMIVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVehiculoActionPerformed(evt);
            }
        });
        jMenu1.add(jMIVehiculo);

        jMISoat.setText("Ingreso SOAT");
        jMISoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISoatActionPerformed(evt);
            }
        });
        jMenu1.add(jMISoat);

        jMenuBar1.add(jMenu1);

        jMRuta.setText("Ruta");

        jMenu2.setText("ruta");
        jMRuta.add(jMenu2);

        jMenuBar1.add(jMRuta);

        jMConsulta.setText("Consulta");

        jMenu5.setText("Lista de estudiantes");
        jMConsulta.add(jMenu5);

        jMenuBar1.add(jMConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAsistente1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jBSoat, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBTecnomecanica, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBLista, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBSoat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBAseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBAsistente1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBTecnomecanica, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)))
                                    .addComponent(jBEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jBLista, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAseguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAseguradoraActionPerformed
    Aseguradora miUsuario = new Aseguradora();
        miUsuario.setVisible(true);
        miUsuario.obIDFunc(idFu);
    }//GEN-LAST:event_jMIAseguradoraActionPerformed

    private void jMIEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIEstudianteActionPerformed

    private void jMIAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAsistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAsistenteActionPerformed

    private void jMIConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConductorActionPerformed
        Conductor miUsuario = new Conductor();
        miUsuario.setVisible(true);
        miUsuario.obIDFunc(idFu);
        
    }//GEN-LAST:event_jMIConductorActionPerformed

    public void obIdFunc(String id){
     idFu=id;   
    }
        
    private void jMIFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFuncionarioActionPerformed
Funcionario miUsuario = new Funcionario();
        miUsuario.setVisible(true);       
    }//GEN-LAST:event_jMIFuncionarioActionPerformed

    private void jMIVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVehiculoActionPerformed
        Vehiculo miUsuario = new Vehiculo();
        miUsuario.setVisible(true);
        miUsuario.obIDFunc(idFu);
    }//GEN-LAST:event_jMIVehiculoActionPerformed

    private void jMISoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISoatActionPerformed
      
        SOAT miUsuario = new SOAT();
        miUsuario.setVisible(true);
        miUsuario.obIDFunc(idFu);
    }//GEN-LAST:event_jMISoatActionPerformed

    private void jBVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVehiculoActionPerformed
        // TODO add your handling code here:
        Vehiculo miUsuario = new Vehiculo();
        miUsuario.setVisible(true);
        miUsuario.obIDFunc(idFu);
     
    }//GEN-LAST:event_jBVehiculoActionPerformed

    private void jBConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConductorActionPerformed
              Conductor miConductor = new Conductor();
              miConductor.setVisible(true);
              miConductor.obIDFunc(idFu);
    }//GEN-LAST:event_jBConductorActionPerformed

    private void jBSoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSoatActionPerformed
            SOAT miSoat = new SOAT();
            miSoat.setVisible(true);
            miSoat.obIDFunc(idFu);
    }//GEN-LAST:event_jBSoatActionPerformed

    private void jBAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsistenteActionPerformed
dispose();        // TODO add your handling code here:

    }//GEN-LAST:event_jBAsistenteActionPerformed

    private void jBFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFuncionarioActionPerformed
                Funcionario miAsistente = new Funcionario();
        miAsistente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFuncionarioActionPerformed

    private void jBEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEstudianteActionPerformed
        // TODO add your handling code here:
        Estudiante miVentana = new Estudiante();
        miVentana.setVisible(true);
        miVentana.obtenerIdFunc(idFu);
     
    }//GEN-LAST:event_jBEstudianteActionPerformed

    private void jBAsistente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsistente1ActionPerformed
        Asistente miAsistente = new Asistente();
        miAsistente.setVisible(true);
        miAsistente.obtenerIdFunc(idFu);    }//GEN-LAST:event_jBAsistente1ActionPerformed

    private void jBRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRutaActionPerformed
        // TODO add your handling code here:
        IngresoRutas miRuta = new IngresoRutas();
        miRuta.setVisible(true);
        //miRuta.ontenerIdFunc(idFu);
    }//GEN-LAST:event_jBRutaActionPerformed

    private void jBAseguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAseguradoraActionPerformed
        
        Aseguradora miAseguradora = new Aseguradora();
        miAseguradora.setVisible(true);
        miAseguradora.obIDFunc(idFu);
        
    }//GEN-LAST:event_jBAseguradoraActionPerformed

    private void jBTecnomecanicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTecnomecanicaActionPerformed
        Tecnomecanica miTecnomecanica = new Tecnomecanica();
        miTecnomecanica.setVisible(true);
        miTecnomecanica.obIDFunc(idFu);
   
    }//GEN-LAST:event_jBTecnomecanicaActionPerformed

    private void jBListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListaActionPerformed
    
        ListaEstudiantes miLista = new ListaEstudiantes();
        miLista.setVisible(true);
        
    }//GEN-LAST:event_jBListaActionPerformed

//    public void cargarCSV() {
//        
//        //crea un objeto filechooser
//        JFileChooser dlg = new JFileChooser();
//        //del objeto creado vamos a llamar el metodo setFileFilter
//        dlg.setFileFilter(filter);
//        //abrimos la ventana de dialogo para escoger imagenes
//        int opcion = dlg.showOpenDialog(this);
//        //si hacemos clic en boton abrir
//        if (opcion == JFileChooser.APPROVE_OPTION) {
//            //obtener el nombre del archivo que hemos seleccionado
//            String fil = dlg.getSelectedFile().getPath();
//            //obtener la direccion donde se guarda la imagen
//            String file = dlg.getSelectedFile().toString();
//            
//
//        try (FileInputStream fis = new FileInputStream(file);
//                InputStreamReader isr = new InputStreamReader(fis, 
//                        StandardCharsets.UTF_8);
//                CSVReader reader = new CSVReader(isr)) {
//            String[] nextLine;
//
//            while ((reader) != null) {
//                
//                nextLine=reader.readNext();
//                
//                            transFuncionario = new E(codigo, ident, nombre, apellido, celular,correo, direccion, grado, ciudad, nomAcu,celAcu,corrAcu,DirecAcu);
//            datosFuncionario.add(transFuncionario);
//                
//
//    }
//    } catch (Exception e) {
//            }
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
public void cerrarConductor(){
    Conductor miUsuario = new Conductor();
        miUsuario.setVisible(false);
}
public void cerrarLicencia(){
    Licencia miUsuario = new Licencia();
        miUsuario.setVisible(false);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAseguradora;
    private javax.swing.JButton jBAsistente;
    private javax.swing.JButton jBAsistente1;
    private javax.swing.JButton jBConductor;
    private javax.swing.JButton jBEstudiante;
    private javax.swing.JButton jBFuncionario;
    private javax.swing.JButton jBLista;
    private javax.swing.JButton jBRuta;
    private javax.swing.JButton jBSoat;
    private javax.swing.JButton jBTecnomecanica;
    private javax.swing.JButton jBVehiculo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMConsulta;
    private javax.swing.JMenuItem jMIAseguradora;
    private javax.swing.JMenuItem jMIAsistente;
    private javax.swing.JMenuItem jMIConductor;
    private javax.swing.JMenuItem jMIEstudiante;
    private javax.swing.JMenuItem jMIFuncionario;
    private javax.swing.JMenuItem jMISoat;
    private javax.swing.JMenuItem jMIVehiculo;
    private javax.swing.JMenu jMRuta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
